// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: etherlink/etherlink/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateEthInput struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgCreateEthInput) Reset()         { *m = MsgCreateEthInput{} }
func (m *MsgCreateEthInput) String() string { return proto.CompactTextString(m) }
func (*MsgCreateEthInput) ProtoMessage()    {}
func (*MsgCreateEthInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_85a00ce634cca2cb, []int{0}
}
func (m *MsgCreateEthInput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateEthInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateEthInput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateEthInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateEthInput.Merge(m, src)
}
func (m *MsgCreateEthInput) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateEthInput) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateEthInput.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateEthInput proto.InternalMessageInfo

func (m *MsgCreateEthInput) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgCreateEthInputResponse struct {
}

func (m *MsgCreateEthInputResponse) Reset()         { *m = MsgCreateEthInputResponse{} }
func (m *MsgCreateEthInputResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateEthInputResponse) ProtoMessage()    {}
func (*MsgCreateEthInputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85a00ce634cca2cb, []int{1}
}
func (m *MsgCreateEthInputResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateEthInputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateEthInputResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateEthInputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateEthInputResponse.Merge(m, src)
}
func (m *MsgCreateEthInputResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateEthInputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateEthInputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateEthInputResponse proto.InternalMessageInfo

type MsgUpdateEthInput struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgUpdateEthInput) Reset()         { *m = MsgUpdateEthInput{} }
func (m *MsgUpdateEthInput) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateEthInput) ProtoMessage()    {}
func (*MsgUpdateEthInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_85a00ce634cca2cb, []int{2}
}
func (m *MsgUpdateEthInput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateEthInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateEthInput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateEthInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateEthInput.Merge(m, src)
}
func (m *MsgUpdateEthInput) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateEthInput) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateEthInput.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateEthInput proto.InternalMessageInfo

func (m *MsgUpdateEthInput) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgUpdateEthInputResponse struct {
}

func (m *MsgUpdateEthInputResponse) Reset()         { *m = MsgUpdateEthInputResponse{} }
func (m *MsgUpdateEthInputResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateEthInputResponse) ProtoMessage()    {}
func (*MsgUpdateEthInputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85a00ce634cca2cb, []int{3}
}
func (m *MsgUpdateEthInputResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateEthInputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateEthInputResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateEthInputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateEthInputResponse.Merge(m, src)
}
func (m *MsgUpdateEthInputResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateEthInputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateEthInputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateEthInputResponse proto.InternalMessageInfo

type MsgDeleteEthInput struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgDeleteEthInput) Reset()         { *m = MsgDeleteEthInput{} }
func (m *MsgDeleteEthInput) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteEthInput) ProtoMessage()    {}
func (*MsgDeleteEthInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_85a00ce634cca2cb, []int{4}
}
func (m *MsgDeleteEthInput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteEthInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteEthInput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteEthInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteEthInput.Merge(m, src)
}
func (m *MsgDeleteEthInput) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteEthInput) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteEthInput.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteEthInput proto.InternalMessageInfo

func (m *MsgDeleteEthInput) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgDeleteEthInputResponse struct {
}

func (m *MsgDeleteEthInputResponse) Reset()         { *m = MsgDeleteEthInputResponse{} }
func (m *MsgDeleteEthInputResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteEthInputResponse) ProtoMessage()    {}
func (*MsgDeleteEthInputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85a00ce634cca2cb, []int{5}
}
func (m *MsgDeleteEthInputResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteEthInputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteEthInputResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteEthInputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteEthInputResponse.Merge(m, src)
}
func (m *MsgDeleteEthInputResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteEthInputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteEthInputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteEthInputResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateEthInput)(nil), "etherlink.etherlink.MsgCreateEthInput")
	proto.RegisterType((*MsgCreateEthInputResponse)(nil), "etherlink.etherlink.MsgCreateEthInputResponse")
	proto.RegisterType((*MsgUpdateEthInput)(nil), "etherlink.etherlink.MsgUpdateEthInput")
	proto.RegisterType((*MsgUpdateEthInputResponse)(nil), "etherlink.etherlink.MsgUpdateEthInputResponse")
	proto.RegisterType((*MsgDeleteEthInput)(nil), "etherlink.etherlink.MsgDeleteEthInput")
	proto.RegisterType((*MsgDeleteEthInputResponse)(nil), "etherlink.etherlink.MsgDeleteEthInputResponse")
}

func init() { proto.RegisterFile("etherlink/etherlink/tx.proto", fileDescriptor_85a00ce634cca2cb) }

var fileDescriptor_85a00ce634cca2cb = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0x2d, 0xc9, 0x48,
	0x2d, 0xca, 0xc9, 0xcc, 0xcb, 0xd6, 0x47, 0xb0, 0x4a, 0x2a, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2,
	0x85, 0x84, 0xe1, 0x62, 0x7a, 0x70, 0x96, 0x94, 0x32, 0x36, 0x2d, 0xa9, 0x25, 0x19, 0xf1, 0x99,
	0x79, 0x05, 0xa5, 0x25, 0x10, 0x9d, 0x4a, 0xba, 0x5c, 0x82, 0xbe, 0xc5, 0xe9, 0xce, 0x45, 0xa9,
	0x89, 0x25, 0xa9, 0xae, 0x25, 0x19, 0x9e, 0x20, 0x29, 0x21, 0x09, 0x2e, 0xf6, 0x64, 0x90, 0x48,
	0x7e, 0x91, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x8c, 0xab, 0x24, 0xcd, 0x25, 0x89, 0xa1,
	0x3c, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15, 0x6a, 0x56, 0x68, 0x41, 0x0a, 0x29, 0x66,
	0xa1, 0x2a, 0x47, 0x33, 0xcb, 0x25, 0x35, 0x27, 0x95, 0x04, 0xb3, 0x50, 0x95, 0xc3, 0xcc, 0x32,
	0x3a, 0xcc, 0xc4, 0xc5, 0xec, 0x5b, 0x9c, 0x2e, 0x94, 0xc1, 0xc5, 0x87, 0xe6, 0x51, 0x35, 0x3d,
	0x2c, 0x01, 0xa7, 0x87, 0xe1, 0x43, 0x29, 0x3d, 0xe2, 0xd4, 0xc1, 0x6c, 0x04, 0xd9, 0x84, 0x16,
	0x0c, 0x38, 0x6d, 0x42, 0x55, 0x87, 0xdb, 0x26, 0xec, 0xe1, 0x04, 0xb2, 0x09, 0x2d, 0x90, 0x70,
	0xda, 0x84, 0xaa, 0x0e, 0xb7, 0x4d, 0xd8, 0x43, 0xd1, 0xc9, 0xf4, 0xc4, 0x23, 0x39, 0xc6, 0x0b,
	0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86,
	0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0xa4, 0x11, 0xc9, 0xab, 0x02, 0x39, 0x75, 0x56, 0x16, 0xa4, 0x16,
	0x27, 0xb1, 0x81, 0xd3, 0x99, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x67, 0xa5, 0xd3, 0xe0, 0xc1,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateEthInput(ctx context.Context, in *MsgCreateEthInput, opts ...grpc.CallOption) (*MsgCreateEthInputResponse, error)
	UpdateEthInput(ctx context.Context, in *MsgUpdateEthInput, opts ...grpc.CallOption) (*MsgUpdateEthInputResponse, error)
	DeleteEthInput(ctx context.Context, in *MsgDeleteEthInput, opts ...grpc.CallOption) (*MsgDeleteEthInputResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateEthInput(ctx context.Context, in *MsgCreateEthInput, opts ...grpc.CallOption) (*MsgCreateEthInputResponse, error) {
	out := new(MsgCreateEthInputResponse)
	err := c.cc.Invoke(ctx, "/etherlink.etherlink.Msg/CreateEthInput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateEthInput(ctx context.Context, in *MsgUpdateEthInput, opts ...grpc.CallOption) (*MsgUpdateEthInputResponse, error) {
	out := new(MsgUpdateEthInputResponse)
	err := c.cc.Invoke(ctx, "/etherlink.etherlink.Msg/UpdateEthInput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteEthInput(ctx context.Context, in *MsgDeleteEthInput, opts ...grpc.CallOption) (*MsgDeleteEthInputResponse, error) {
	out := new(MsgDeleteEthInputResponse)
	err := c.cc.Invoke(ctx, "/etherlink.etherlink.Msg/DeleteEthInput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateEthInput(context.Context, *MsgCreateEthInput) (*MsgCreateEthInputResponse, error)
	UpdateEthInput(context.Context, *MsgUpdateEthInput) (*MsgUpdateEthInputResponse, error)
	DeleteEthInput(context.Context, *MsgDeleteEthInput) (*MsgDeleteEthInputResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateEthInput(ctx context.Context, req *MsgCreateEthInput) (*MsgCreateEthInputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEthInput not implemented")
}
func (*UnimplementedMsgServer) UpdateEthInput(ctx context.Context, req *MsgUpdateEthInput) (*MsgUpdateEthInputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEthInput not implemented")
}
func (*UnimplementedMsgServer) DeleteEthInput(ctx context.Context, req *MsgDeleteEthInput) (*MsgDeleteEthInputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEthInput not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateEthInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateEthInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateEthInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etherlink.etherlink.Msg/CreateEthInput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateEthInput(ctx, req.(*MsgCreateEthInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateEthInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateEthInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateEthInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etherlink.etherlink.Msg/UpdateEthInput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateEthInput(ctx, req.(*MsgUpdateEthInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteEthInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteEthInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteEthInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etherlink.etherlink.Msg/DeleteEthInput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteEthInput(ctx, req.(*MsgDeleteEthInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "etherlink.etherlink.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEthInput",
			Handler:    _Msg_CreateEthInput_Handler,
		},
		{
			MethodName: "UpdateEthInput",
			Handler:    _Msg_UpdateEthInput_Handler,
		},
		{
			MethodName: "DeleteEthInput",
			Handler:    _Msg_DeleteEthInput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "etherlink/etherlink/tx.proto",
}

func (m *MsgCreateEthInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateEthInput) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateEthInput) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateEthInputResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateEthInputResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateEthInputResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateEthInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateEthInput) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateEthInput) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateEthInputResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateEthInputResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateEthInputResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteEthInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteEthInput) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteEthInput) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteEthInputResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteEthInputResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteEthInputResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateEthInput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateEthInputResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateEthInput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateEthInputResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteEthInput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteEthInputResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateEthInput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateEthInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateEthInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateEthInputResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateEthInputResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateEthInputResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateEthInput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateEthInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateEthInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateEthInputResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateEthInputResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateEthInputResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteEthInput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteEthInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteEthInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteEthInputResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteEthInputResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteEthInputResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
